version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - '27017:27017'
    networks:
      - chatbot-network

  profin-chatbot:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - SQL_HOST=10.14.116.10
      - SQL_PORT=1433
      - SQL_USERNAME=erev_uat
      - SQL_PASSWORD=4dm1nd@12356890a!@#$
      - SQL_DATABASE=DDC_EREV_UAT
      - MONGODB_URI=mongodb://mongo:27017/ChatbotDB
    depends_on:
      - mongo
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
