name: CI/CD for NestJS dev branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # NestJS thường chạy tốt Node 16+ nên bạn chọn phiên bản phù hợp

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to staging server
        env:
          SSH_PRIVATE_KEY: 'awm;mG9]1xB0*S`>0Z5D7(qjfJB<2*'
          SSH_USER: 'admin'
          SSH_HOST: '10.15.142.23'
          REMOTE_PATH: '/home/admin/CD-TEST'
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            cd $REMOTE_PATH
            git pull origin dev
            npm ci
            npm run build
            pm2 restart nestjs-app || pm2 start dist/main.js --name nestjs-app
          EOF
